---
title: "git_00"
author: "mariahlynn"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“What may I do?” at length I cried,


Tired of the painful task.

The fairy quietly replied,


And said, “You must not ask.”
 
“Rules and Regulations,” in addition to commenting upon correctness in writing, also contains remonstrations. 
It refers to the problem of stammering, which plagued Dodgson throughout his life, emphasizing his shyness and becoming a major factor when he considered acceptance of any public-speaking engagements   


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,    

And sorry I could not travel both  

And be one traveler, long I stood  

And looked down one as far as I could  

To where it bent in the undergrowth; 
 

Then took the other, as just as fair,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      
Shining with all his might:  

He did his very best to make  
      
The billows smooth and bright —  

And this was odd, because it was  
      
The middle of the night.  


The moon was shining sulkily,  
    
  Because she thought the sun  

Had got no business to be there  
    
  After the day was done —    

"It's very rude of him," she said,    
   
   "To come and spoil the fun."       


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Inexplicable, the sign outside a deli scrawled
with FLOWERS
                                 and below that: ALWAYS.
But there were no flowers. And I have never
seen an Always. I would like to,
                                              and I have looked.
I have kept my eye keen
                                        for Always, have liked
its idea like an expensive purse, coveting it as
it appears,
            riding the arms of rich ladies who are
so very lady.                      I've rolled on velvet
            cushions where I heard Always slept,
and I once tried to kiss Always,
                  but I don't think it was the Always
I was looking for.
I like your Always, it looks
such a demanding pet. It looks like it kisses
nice and soft.
                         It looks like the bruise I found
flowering on my knee.
                                    I fell down at your voice.
Not to worry, I got right back up, walked ten
more blocks
                     and by then I was halfway home.
I knock my knees blue
                                         and scabbed crawling
toward you, wanting flowers,
                               and always, always, always
to slide against the cold vinyl of a car's seat,
your pale hands
                            on the bare backs of my legs,
that's one Always I want, and whoever knew
there were so many species
                              of Always? Your bare hands
on the pale backs
                            of my thighs, printing bruise,
and if you said Flowers, said Always and we
could erect a forever
                                    of something like sheets
                         and breakfast and an ordinary
day, my eyes would
                always slide across the table toward
you,
       to warm their twin marbles in your palm,
my face would flower
                          for you daily, so that when we
die, roses might petal
                                themselves out our throats.  

